# .github/workflows/test-and-report.yml

name: Test & Report

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    name: Run ${{ matrix.flow }} / ${{ matrix.test_type }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flow: [consumer, provider]
        test_type: [smoke, functional, mobile]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest for ${{ matrix.flow }} / ${{ matrix.test_type }}
        run: |
          pytest \
            tests/${{ matrix.flow }}/${{ matrix.test_type }} \
            --json-report \
            --json-report-file=report-${{ matrix.flow }}-${{ matrix.test_type }}.json \
            -q

      - name: Upload JSON report artifact
        uses: actions/upload-artifact@v2
        with:
          name: report-${{ matrix.flow }}-${{ matrix.test_type }}
          path: report-${{ matrix.flow }}-${{ matrix.test_type }}.json

  coverage:
    name: Coverage & Summary Report
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full test suite under coverage
        run: |
          coverage run -m pytest

      - name: Produce coverage report
        run: |
          coverage report --fail-under=80

      - name: Generate HTML coverage report
        run: |
          coverage html

      - name: Generate JSON & human-readable test report
        run: |
          python report_generator.py

      - name: Upload coverage & test-report artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-and-report
          path: |
            report.json
            TEST_REPORT.md
            TEST_REPORT.pdf
            htmlcov/
